### ISSUE TITLE
[Epic-ish] Settings page

### ISSUE THREAD

**Issue by pingzing** [pingzing/digi-transit-10#12]
Should contain the following elements:
- [x] Default search settings--always leave "From My Location", default transit modes, default optimization strategy, etc
- [x] Special thanks
- [x] License text
- [x] Version number
- [x] Turn off telemetry
- [x] Theme switching
- [x] Number of pinned favorites on main page
