### ISSUE TITLE
[Epic] Favorites

### ISSUE THREAD

**Issue by pingzing** [pingzing/digi-transit-10#2]
Add or Edit dialog:
- [x] Add map stuff

Favorite Places:
- [x] Add favorites from search box
- [x] Select favorites from search box
- [x] Show custom favorite icons in MainPage Favorites list
- [x] Add an Edit Favorite UI
- [x] Add Favorite Place button that pops up a DigiTransitSearchBox and allows you to find a place, set its icon, and name
- [x] Edit place popup that allows you to change its icon and name.
- [x] Refactor PinnedFavorites to just be a list of IDs pointing to favorites, rather than being a fully separate list all its own

Favorite Routes:
- [x] Add favorite routes from the TripPlanResult page/section
- [x] Select favorite routes from the Favorites pivot/section
- [x] Show favorite routes in the MainPage Favorites list
- [x] Add an Edit Favorite Route UI

Favorites Page
- [x] Make tapping a favorite place navigate to the MainPage,  add it to the To field, and immediately Plan a trip (if able)
- [x] Make tapping a favorite route navigate to the MainPage, set all legs to the selected Route, and immediately Plan a trip
- [x] Add wide visual state command bar
- [x] Change command bar when in multi-selection state
- Add context-menus for Places that allow:
  - [x] Select
  - [x] Set as origin
  - [x] Set as destination
  - [x] Edit
  - [x] Delete
  - [x] Pin to Start
  - [x] Pin to Main Page
- Add context-menus for Routes that allow
  - [x] Select
  - [x] Plan route
  - [x] Edit
  - [x] Delete
  - [x] Pin to Main Page
  - [x] Pin to Start

**Comment by pingzing** [comment]
Need to rework the underlying data model--keeping Favorites, Favorite Routes, etc in Settings isn't viable--CompositeSettings aren't large enough for the kind of data storage we're looking at. Gotta roll our own FavoritesService that handles dealing with the filesystem ourselves.

Note: Favorites and Favorite Routes at least should roam.

That, or radically shrink the size of our favorites.

**Comment by pingzing** [comment]
Above comment is done. We have a FavoritesService now that serializes favorites out to disk AND compresses them for good measure \o/

**Comment by pingzing** [comment]
Done! Finally!
