### ISSUE TITLE
[Epic] Search page

### ISSUE THREAD

**Issue by pingzing** [pingzing/digi-transit-10#6]
Add page that:
- Displays nearby stops
- Allows searching for Lines by name
- Allows searching for stops by name

Not sure if we should reuse the FloatingPanel paradigm, or make it a master-detail style view.

**Comment by pingzing** [comment]
Now that I've gotten started, I can outline more of todo list:

## Overall tasks

- [x]  Break each pivot into its own ViewModel
- [x]  Make the parent ViewModel bind to the pivot with an ObservableCollection of the children ViewModels
- [x]  Figure out a less-buggy way to bind locations to the map
~~Experiment with hanging the FloatingPanel from the top of the page~~ No, bottom is fine for now.

### Nearby Stops & Stops

- [x] When selecting a stop, center it on the Map, and focus its MapIcon (somehow. Either swap out the bitmap, or just give up and use XAML controls on the MapControl)
- [x] Allow selection of stops by tapping on their MapIcons
- [x] Make the list of lines in the "More Details" page link to the given line
-  [x] If the More Details page for a given stop has no upcoming transit stops, show a friendly "No line stops here within the next <X> hours" message

## Lines

~~(Maybe not?) Find a way of displaying some kind of schedule information here~~ Nah.
- [x] Allow this section to receive search requests from other parts of the app
